name: Update VPN Configs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  update-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Switch to auto-source branch, create if not exists
        run: |
          git checkout auto-source || git checkout -b auto-source

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('source/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create virtual environment
        run: python -m venv venv --copies

      - name: Upgrade pip
        run: ./venv/bin/python -m pip install --upgrade pip

      - name: Install requirements
        run: ./venv/bin/python -m pip install -r source/requirements.txt

      - name: Run main script
        run: ./venv/bin/python source/main.py

      - name: Configure Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      - name: Check for changes
        run: |
          git status
          git diff --stat

      - name: Commit & Push auto-source
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update VPN configs"
            git push origin auto-source
          else
            echo "✅ No file changes, skip commit and push."
          fi
